package com.huydq.demo.model;

// default package
// Generated Mar 27, 2019 5:27:12 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Accounts generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNTS", schema = "C##MYSHOP")
public class Accounts implements java.io.Serializable {

	private String userName;
	private boolean active;
	private String passwords;
	private String roles;

	public Accounts() {
	}

	public Accounts(String userName, boolean active, String passwords, String roles) {
		this.userName = userName;
		this.active = active;
		this.passwords = passwords;
		this.roles = roles;
	}

	@Id

	@Column(name = "USER_NAME", unique = true, nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 1, scale = 0)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "PASSWORDS", nullable = false, length = 128)
	public String getPasswords() {
		return this.passwords;
	}

	public void setPasswords(String passwords) {
		this.passwords = passwords;
	}

	@Column(name = "ROLES", nullable = false, length = 20)
	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

}
