package com.huydq.demo.model;

// default package
// Generated Mar 27, 2019 5:27:12 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTS", schema = "C##MYSHOP")
public class Products implements java.io.Serializable {

	private String id;
	private String image;
	private String name;
	private double price;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Products() {
	}
	
	

	public Products(String id, String image, String name, double price) {
		super();
		this.id = id;
		this.image = image;
		this.name = name;
		this.price = price;
	}



	public Products(String id, String name, double price) {
		this.id = id;
		this.name = name;
		this.price = price;
	}

	public Products(String id, String image, String name, double price, Set<OrderDetails> orderDetailses) {
		this.id = id;
		this.image = image;
		this.name = name;
		this.price = price;
		this.orderDetailses = orderDetailses;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "IMAGE")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRICE", nullable = false, precision = 126, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}
@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "products")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
